# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            plb
tagline:          ''
description:      'Stories about people, places and the choices that shaped my life.'
url:              https://patito.github.io
baseurl:          https://patito.github.io/

author:
  name:           'Paulo Leonardo Benatto'
  url:            https://twitter.com/pbenatto

paginate:         5
plugins:          [jekyll-paginate]
